name: Production Build

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: NPM Install
        run: |
          npm ci
      - name: Production Build
        run: |
          npm run build
      - name: S3 Copy
        uses: prewk/s3-cp-action@v0.1.1
        with:
          args: >
            --recursive
            --exclude "*"
            --include "static/*"
            --include "*.js"
            --include "*.js.map"
            --include "*.css"
            --exclude "sw.js"
            --metadata-directive REPLACE
            --cache-control public,max-age=31536000
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE: public
          DEST: s3://${{ secrets.AWS_S3_BUCKET }}
      - name: S3 Copy
        uses: prewk/s3-cp-action@v0.1.1
        with:
          args: >
            --recursive
            --exclude "static/*"
            --exclude "*.js"
            --exclude "*.js.map"
            --exclude "*.css"
            --include "sw.js"
            --metadata-directive REPLACE
            --cache-control public,max-age=0,must-revalidate
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE: public/index.html
          DEST: s3://${{ secrets.AWS_S3_BUCKET }}/index.html
