name: Production Build

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: NPM Install
        run: |
          npm ci
      - name: Production Build
        run: |
          npm run build
      - name: S3 Copy
        uses: prewk/s3-cp-action@v2
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          source: public
          dest: s3://${{ secrets.AWS_S3_BUCKET }}
          flags: >
            --recursive
            --exclude "*"
            --include "static/*"
            --include "*.js"
            --include "*.js.map"
            --include "*.css"
            --exclude "sw.js"
            --metadata-directive REPLACE
            --cache-control public,max-age=31536000
      - name: S3 Copy
        uses: prewk/s3-cp-action@v2
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          source: public/index.html
          dest: s3://${{ secrets.AWS_S3_BUCKET }}/index.html
          flags: >
            --recursive
            --exclude "static/*"
            --exclude "*.js"
            --exclude "*.js.map"
            --exclude "*.css"
            --include "sw.js"
            --metadata-directive REPLACE
            --cache-control public,max-age=0,must-revalidate
